FROM registry.cn-beijing.aliyuncs.com/niao-jmeter/jmeter-base:1.0.0

MAINTAINER niaoshuai <niao.shuai123@163.com>
	
ADD JMeter-InfluxDB-Writer-plugin-1.2.jar ${JMETER_HOME}/lib/ext 
ADD jmeter-plugins-casutg-2.8.jar ${JMETER_HOME}/lib/ext
